
theme: light

menu:
  Home: /
  Archives: /archives

profile:
  name: Chinmoku
  introduction: Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.

contact:
  email: xfc_exclave@163.com

hello:
  title: Hello, I'm %s, welcome to my blog.
  subtitle: A free and fully responsive site template
  brif_intro: Aenean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  
sidebar:
  title: Chinmoku
  menu:
    home:
      title: Home
      target: /
    archives:
      title: Archives
      target: /archives
    categories:
      title: Categories
      target: /categories
    link:
      title: Links
      sub: true
      subMenu:
        friends:
          title: Friends
          target: /friends
        website:
          title: Website
          target: /website
    about:
      title: About
      target: /about
  recommends:
  - computer-science/java-learning-path/1-basic/01-java-basic
  - computer-science/web/react-tutorial
  - computer-science/python/django-tutorial
topics:
  java:
    title: A cup of coffee
    icon: fab fa-java
    description: Mainly used to record the notes in the process of java learning.
    target:
  web:
    title: Improve your aesthetic
    icon: fab fa-html5
    description: Mainly used to record the notes in the process of java learning.
    target:
  python:
    title: Life is short, use Python
    icon: fab fa-python
    description: Mainly used to record the notes in the process of java learning.
    target:
  language:
    icon: fa-solid fa-language
    title: Language is an endless river
    description: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
    target:
